(() => {
  "use strict";

  const g = (typeof window !== "undefined") ? window : globalThis;
  const OBSTRAL = g.OBSTRAL || (g.OBSTRAL = {});
  if (OBSTRAL.sandbox) return;

  function normalizePathSep(p) {
    return String(p || "")
      .replace(/\\/g, "/")
      .replace(/\/+/g, "/");
  }

  function safeThreadId(id) {
    // Thread ids are generated by uid(), but keep this defensive.
    return String(id || "").replace(/[^a-zA-Z0-9_-]/g, "");
  }

  function safeWorkdir(workdir) {
    const w0 = normalizePathSep(String(workdir || "")).trim();
    const w = w0.replace(/^\/+|\/+$/g, "");
    if (!w) return "";
    if (/^\//.test(w)) return "";
    if (/^[a-zA-Z]:[\\/]/.test(w)) return "";
    if (/(^|\/)\.\.(\/|$)/.test(w)) return "";
    // Avoid confusing control characters.
    if (/[\u0000-\u001f]/.test(w)) return "";
    return w;
  }

  function resolvedThreadRoot(toolRoot, threadId) {
    const root0 = String(toolRoot || "").trim();
    if (!root0) return undefined;
    const root = normalizePathSep(root0).replace(/\/+$/g, "");
    // Default scratch dir: isolate each thread to avoid collisions + nested git repo disasters.
    if (root === ".tmp" || root === "./.tmp") {
      const tid = safeThreadId(threadId);
      if (!tid) return ".tmp";
      return `.tmp/${tid}`;
    }
    return root0;
  }

  function resolvedCwd(toolRoot, threadId, workdir) {
    const root0 = resolvedThreadRoot(toolRoot, threadId);
    if (!root0) return undefined;
    const wd = safeWorkdir(workdir);
    if (!wd) return root0;
    const base = normalizePathSep(String(root0)).replace(/\/+$/g, "");
    return base + "/" + wd;
  }

  OBSTRAL.sandbox = {
    normalizePathSep,
    safeThreadId,
    safeWorkdir,
    resolvedThreadRoot,
    resolvedCwd,
  };
})();

